[package]
name = "rust-tcp-server"
version = "0.1.0"
authors = ["tonytao <taotao8851@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
